Configuring Ansible:
  The behavior of an Ansible installation can be customized by modifying settings in the Ansible
configuration file. Ansible chooses its configuration file from one of several possible locations on
the control node.
Using /etc/ansible/ansible.cfg:
  The ansible package provides a base configuration file located at /etc/ansible/ansible.cfg.
This file is used if no other configuration file is found.
Using ~/.ansible.cfg:
  Ansible looks for a .ansible.cfg file in the user's home directory. This configuration is used
instead of the /etc/ansible/ansible.cfg if it exists and if there is no ansible.cfg file in
the current working directory.
Using ./ansible.cfg:
  If an ansible.cfg file exists in the directory in which the ansible command is executed, it is
used instead of the global file or the user's personal file. This allows administrators to create a
directory structure where different environments or projects are stored in separate directories,
with each directory containing a configuration file tailored with a unique set of settings.

Example of ansible.cfg:
  [defaults]
  inventory = ./inventory
  remote_user = someuser
  ask_pass = false
  [privilege_escalation]
  become = true
  become_method = sudo
  become_user = root
  become_ask_pass = false

commands:
  ansible --version -> see the configuration file used
  

