Writing and Running Playbooks:

Playbook Examples:

- With one play:
---
- name: Install and start Apache HTTPD
  hosts: web
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    - name: correct index.html is present
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

- With two plays:

---
# This is a simple playbook with two plays
- name: first play
  hosts: web.example.com
  tasks:
    - name: first task
      yum:
        name: httpd
        status: present
    - name: second task
      service:
        name: httpd
        enabled: true
        
- name: second play
  hosts: database.example.com
  tasks:
    - name: first task
      service:
        name: mariadb
        enabled: true


commands:
  - ansible-playbook site.yml - run a playbook
  -  ansible-playbook --syntax-check webserver.yml - verify ansible syntax
  - -v -vv -vvv -vvvv - increase verbosity
  - ansible-playbook -C webserver.yml - dryrun an ansible playbook